---

- name: packages
  apt: >
      pkg={{ item }}
      state=present
  with_items:
      - xvfb
  sudo: yes

- name: service template
  template: >
      src=xvfbd.j2
      dest=/etc/init.d/xvfbd
  sudo: yes

- name: service file
  file: >
      path=/etc/init.d/xvfbd
      state=file
      group=root
      owner=root
      mode=0755
  sudo: yes

- name: service install
  shell: >
      /usr/sbin/update-rc.d xvfbd defaults
      creates=/etc/rc0.d/K01xvfbd
  sudo: yes

- name: service
  service: >
      name=xvfbd
      state=started
      enabled=true
  sudo: yes

- name: user profiles display
  lineinfile: >
      dest={{ item }}
      line="export DISPLAY=:99"
      regexp="^export DISPLAY="
  with_items: user_profiles
  sudo: no
