---
- hosts: all
  sudo: yes
  vars:
    user: vagrant
  roles:
    - base/debian
    - git/debian
    - ssh/debian
    - repository/debian/dotdeb
    - build/debian
    - sass/debian
    - bower/debian
    - nginx/debian
    - mysql/debian
    - oh-my-zsh/debian

  tasks:

  # Php 5
  - name: php5 packages
    apt: >
      pkg={{ item }}
      state=present
    with_items:
      - php5-fpm
      - php5-cli
    notify: nginx restart
  - name: php5 extra packages
    apt: >
      pkg={{ item }}
      state=present
    with_items:
      - php5-intl
      - php5-mysqlnd
      - php5-gd
    notify: php5 fpm restart
  - name: php5 fpm nginx config
    template: >
      src=templates/nginx/php5-fpm.conf.j2
      dest=/etc/nginx/conf.d/php5-fpm.conf
    notify:
      - php5 fpm restart
      - nginx restart
  - name: php5 fpm nginx permissions
    template: >
      src=templates/nginx/permissions.conf.j2
      dest=/etc/php5/fpm/pool.d/permissions.conf
    notify:
      - php5 fpm restart
      - nginx restart
  - name: php5 fpm nginx timeout
    template: >
      src=templates/nginx/timeout.conf.j2
      dest=/etc/php5/fpm/pool.d/timeout.conf
    notify:
      - php5 fpm restart
      - nginx restart
  - name: php5 config memory fpm
    template: >
      src=templates/php/memory.ini.j2
      dest=/etc/php5/fpm/conf.d/100_memory.ini
    notify: php5 fpm restart
  - name: php5 config memory cli
    template: >
      src=templates/php/memory.ini.j2
      dest=/etc/php5/cli/conf.d/100_memory.ini
  - name: php5 config date fpm
    template: >
      src=templates/php/date.ini.j2
      dest=/etc/php5/fpm/conf.d/100_date.ini
    notify: php5 fpm restart
  - name: php5 config date cli
    template: >
      src=templates/php/date.ini.j2
      dest=/etc/php5/cli/conf.d/100_date.ini

  # Nginx Virtual Host
  - name: nginx virtual host conf
    template: >
      src=templates/nginx/vhost.conf.j2
      dest=/etc/nginx/sites-available/vhost_default
  - name: nginx enable virtual host conf
    shell: >
      ngxensite vhost_default
      creates=/etc/nginx/sites-enabled/vhost_default
    notify: nginx restart

  # Php 5 Dev
  - name: php5 extra packages dev
    apt: >
      pkg={{ item }}
      state=present
    with_items:
      - php5-xdebug
      - php5-xsl
      - php5-curl
    notify: php5 fpm restart
  - name: php5 config xdebug fpm
    template: >
      src=templates/php/xdebug.ini.j2
      dest=/etc/php5/fpm/conf.d/100_xdebug.ini
    notify: php5 fpm restart
  - name: php5 config xdebug cli
    template: >
      src=templates/php/xdebug.ini.j2
      dest=/etc/php5/cli/conf.d/100_xdebug.ini
  - name: php5 config short_open_tag fpm
    template: >
      src=templates/php/short_open_tag.ini.j2
      dest=/etc/php5/fpm/conf.d/100_short_open_tag.ini
    notify: php5 fpm restart
  - name: php5 config short_open_tag cli
    template: >
      src=templates/php/short_open_tag.ini.j2
      dest=/etc/php5/cli/conf.d/100_short_open_tag.ini
  - name: php5 config errors fpm
    template: >
      src=templates/php/errors.ini.j2
      dest=/etc/php5/fpm/conf.d/100_errors.ini
    notify: php5 fpm restart
  - name: php5 config errors cli
    template: >
      src=templates/php/errors.ini.j2
      dest=/etc/php5/cli/conf.d/100_errors.ini

  # Composer
  - name: composer install
    shell: >
      curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f /home/{{ user }}/composer.phar /usr/local/bin/composer
      creates=/usr/local/bin/composer

  # Project
  - name: project profile template
    template: >
      src=templates/project/profile.sh.j2
      dest=/etc/profile.d/project.sh
    sudo: yes
  - name: project profile file
    file: >
      path=/etc/profile.d/project.sh
      state=file
      owner=root
      group=root
      mode=0644
    sudo: yes
  - name: project root
    file: >
      path=/home/{{ user }}
      state=directory
      group=www-data
      mode=0710
  - name: project cache
    file: >
      path=/home/{{ user }}/cache
      state=directory
    sudo: no
  - name: project logs
    file: >
      path=/home/{{ user }}/logs
      state=directory
    sudo: no

  # Acl (Should be simplified with ansible 1.4)
  - name: acl package
    apt: >
      pkg=acl
      state=present
  - name: acl dirs
    shell: >
      setfacl -R -m u:www-data:rwX -m u:{{ user }}:rwX /home/{{ user }}/cache /home/{{ user }}/logs && setfacl -dR -m u:www-data:rwx -m u:{{ user }}:rwx /home/{{ user }}/cache /home/{{ user }}/logs

  handlers:

    # Php 5 Fpm
    - name: php5 fpm restart
      service: >
        name=php5-fpm
        state=restarted

