---

- name: ansible provision time
  shell: >
    /bin/date > /etc/ansible_provision_time
    creates=/etc/ansible_provision_time
  notify: apt update
  sudo: yes

- meta: flush_handlers

- name: packages
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - python-pycurl
  sudo: yes
