---

- hosts: all

  roles:
    - { role: elao.base }
    - { role: elao.php }
    - { role: elao.composer }
    - { role: elao.mysql-server }
    - { role: elao.node }
    - { role: elao.bower }
    - { role: elao.gulp }
    - { role: elao.sass }
    - { role: elao.image }
    - { role: elao.projects }

- hosts: dev

  roles:
    - { role: elao.ohmyzsh }
    - { role: elao.php-xdebug }
    - { role: elao.php-phpunit }
    - { role: elao.php-phpcs }
    - { role: elao.sass-scsslint }
    - { role: elao.phantomjs }
    - { role: elao.mailcatcher }
    - { role: elao.capifony }
